services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: zero_gorm_code
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - zero-gorm-network

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - zero-gorm-network

  zero-gorm-code:
    build:
      context: .
      dockerfile: Dockerfile
    image: zero-gorm-code   # 👈 加上这一行，强制指定生成的镜像名字和标签
    container_name: zero-gorm-code
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./etc:/app/etc
    command: ["./zero-app", "-f", "etc/config.yaml"]
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - zero-gorm-network

volumes:
  postgres_data:
  redis_data:

networks:
  zero-gorm-network:
    driver: bridge