apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: go-zero-gorm-code-pdb
  namespace: go-zero-gorm-code
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: go-zero-gorm-code-api
